### ISSUE TITLE
Doens't work with ActiveRecord 3.0.3

### ISSUE THREAD

**Issue by ashb** [matthuhiggins/foreigner#41]
I get the following error:

```
undefined method `foreign_key' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x00000101616e38>
```

Looking at dwilkie's fork it seems he has a Foreigner::ConnectionAdapters::TableDefinition module as well as a Table module. Unfortunately his fork doesn't support mysql2 gem currently.
