### ISSUE TITLE
Foreigner doesn't work with Padrino 0.12.0

### ISSUE THREAD

**Issue by kofronpi** [matthuhiggins/foreigner#137]
Hello,
I am using Padrino 0.12.0 with ActiveRecord 3.2.0 and a postgreSQL adapter. I required the gem in the Gemfile and tried to create a foreign key in the "create table".

It throws me an error : 

```
undefined method `foreign_key' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter::TableDefinition:0x0000000344b170>
```

I saw in past issues that support for Padrino was added in issue #76 . Maybe it's broken because of changes in the Padrino framework?
